name: sarmayex
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  equatable: ^2.0.8
  get_it: ^8.3.0
  injectable: ^2.5.1
  dio: ^5.9.2
  rxdart: ^0.28.0
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.11
  freezed: 2.4.7
  analyzer: 6.4.1
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true


